package practice;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;
import utils.JavaScriptUtil;

public class JavaScriptExecutorConcept {

	static WebDriver driver;
	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		
		WebDriverManager.chromedriver().setup();
		 driver = new ChromeDriver();
		 driver.get("https://www.freshworks.com");
		 
		 JavascriptExecutor js = (JavascriptExecutor)driver;
//		 js.executeScript(Key, args);
		 String title  = js.executeScript("return document.title").toString();
		 System.out.println(title);
		 
		 JavaScriptUtil jsUtil = new JavaScriptUtil(driver);
		 String title1 = jsUtil.getTitleByJS();
		 System.out.println(title);
		 
		 //This will give all the text on a page
		 //Useful for content testing
		 String pageText = jsUtil.getPageInnerText();
		 if(pageText.contains("Alex Bookless")) {
			 System.out.println("pass");
		 }
		 
		 //generate own alert
		 //Doesn't return anything
		// jsUtil.generateAlert("alert generated by JS");
		 
		// jsUtil.refreshBrowserByJS();
		 //history.go(0) //used for refresh using js in console
		 
		 WebElement ele = driver.findElement(By.xpath("//h1[text()='Delight made easy']"));
//		 jsUtil.drawBorder(ele);
		 
		//highlight the element
//		 jsUtil.flash(ele);
		 
//		 jsUtil.scrollPageDown();
//		 Thread.sleep(1000);
//		 jsUtil.scrollPageUp();
//		 Thread.sleep(1000);
//		 
//		 jsUtil.scrollPageDown();
//		 Thread.sleep(1000);
//		 jsUtil.scrollIntoView(ele);
//		 
//		 Thread.sleep(1000);
//		 jsUtil.scrollPageDown("700");
		
		 //click
//		 example for google
//		 if you are getting ElementNotInterceptedException or element not clickable
		 WebElement searchField = driver.findElement(By.name("q"));
		 jsUtil.clickElementByJS(searchField);
				 
		 
		 

	}

}
